[package]
name = "s3-event-bridge"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
aws-config = "0.55.1"
aws-sdk-s3 = "0.26.0"
aws-smithy-types-convert = { version = "0.55.1", features = ["convert-chrono"] }
aws_lambda_events = { version = "0.7.3", default-features = false, features = ["s3", "sqs"] }
base64ct = { version = "1.6.0", features = ["alloc"] }
chrono = { version = "0.4.24", features = ["serde"] }
envy = "0.4.2"
jq-rs = { version = "0.4.1" }
lambda_runtime = "0.7"
once_cell = "1.17.1"
regex = "1.7.1"
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.96"
sha1 = "0.10.5"
shell-words = "1.1.0"
tempfile = "3.4.0"
tokio = { version = "1", features = ["macros", "process", "rt", "fs", "io-util"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
