[package]
name = "s3-event-bridge"
version = "0.1.1"
edition = "2021"

# Starting in Rust 1.62 you can use `cargo add` to add dependencies 
# to your project.
#
# If you're using an older Rust version,
# download cargo-edit(https://github.com/killercup/cargo-edit#installation) 
# to install the `add` subcommand.
#
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.

[dependencies]
anyhow = "1.0.69"
aws-config = "0.54.1"
aws-sdk-s3 = "0.24.0"
aws_lambda_events = { version = "0.7.3", default-features = false, features = ["s3", "sqs"] }
base64ct = { version = "1.6.0", features = ["alloc"] }
envy = "0.4.2"
lambda_runtime = "0.7"
once_cell = "1.17.1"
regex = "1.7.1"
serde = { version = "1.0.154", features = ["derive"] }
sha1 = "0.10.5"
shell-words = "1.1.0"
tempfile = "3.4.0"
tokio = { version = "1", features = ["macros", "process", "rt", "fs", "io-util"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }

